/camera_node:
  ros__parameters:
    camera_name: gimbal_camera
    camera_info_url: package://solais_bringup/configs/camera_info.yaml
    config_path: /workspaces/isaac_ros-dev/src/Meta-Vision-SolaisNG/solais_camera/configs/meta_infrantry_camprofile.config
    camera_serial_number: '041010720626'

# /serial_driver:
#   ros__parameters:
#     timestamp_offset: 0.006
#     device_name: /dev/ttyACM0
#     baud_rate: 115200
#     flow_control: none
#     parity: none
#     stop_bits: "1"

/armor_detector:
  ros__parameters:
    camera_name: gimbal_camera
    debug: true

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    # ignore_classes: ["negative"]